version: "3.8"
services:
  app:
    image: ryanmalesic/mu-csci-406-lab7-app
    depends_on:
      - mongo
    environment:
      PORT: ${PORT}
      SECRET: ${SECRET}
    ports:
      - ${PORT}:${PORT}
    restart: always

  mongo:
    image: mongo
    restart: always
